name: timeseriesbook
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - nodejs
  - r-base=4.0.3
  - r-irkernel=1.1*
  - r-latex2exp=0.4.0
  - r-lmtest=0.9_38
  - r-car=3.0_0
  - pip:
    - -r ../book/requirements.txt
    - rpy2==3.4.2
