name: timeseriesbook
channels:
  - conda-forge
  - defaults
  - eoas_ubc
dependencies:
  - python=3.7
  - nodejs
  - r-base=4.0.3
  - r-irkernel=1.1*
  - r-latex2exp=0.4.0
  - rpy2=3.4.2
  - pip:
    - -r ../book/requirements.txt
