title: Análisis de series de tiempo utilizando Python
author: Sebastian Gonzalez y Rodolfo casadiego
copyright: "2021"
logo: images/logo.png

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/sebastiangonzalezv/timeseriesbook-es
  branch: main
  path_to_book: book

launch_buttons:
  notebook_interface: "classic"
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  thebe: false

latex:
  latex_engine: xelatex
  latex_documents:
    targetname: book.tex

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    nb_custom_formats:
      .Rmd:
        - jupytext.reads
        - fmt: Rmd
    language: es

execute:
  execute_notebooks: force


html:
    favicon: images/favicon.ico
    home_page_in_navbar: true
    navbar_number_sections: false
    use_edit_page_button: false
    use_repository_button: true
    use_issues_button: false

parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    # - html_image
    - linkify
    - replacements
    # - smartquotes
    - substitution